### ISSUE TITLE
MANO framework components publish invalid messages

### ISSUE THREAD

**Issue by bjoluc** [CN-UPB/Pishahang#15]
Currently, the default content type for messages published by the `ManoBrokerConnection` class is [`application/json`](https://github.com/CN-UPB/Pishahang/blob/55ba2371ad7546467a95c4789d508bfd5c64a626/mano-framework/base/manobase/messaging.py#L100-L135), while MANO plugins often use `yaml.dump` and `json.dumps` for the payloads interchangeably without specifying the content type. This results in messages that have a yaml body with a json content type. The other way around, payloads of received messages are often blindly parsed as yaml.

Since most of the MANO plugins' interaction with the messaging utilities has to be modified anyway to fix this, refactoring [messaging.py](https://github.com/CN-UPB/Pishahang/blob/55ba2371ad7546467a95c4789d508bfd5c64a626/mano-framework/base/manobase/messaging.py) to handle serialization, deserialization, and content types seems to be a clean solution to me. This way, we can also remove the redundant calls to serialization and deserialization functions throughout all MANO components.

**Comment by hadik3r** [comment]
Agreed!
