### ISSUE TITLE
Redundancy in schema definitions

### ISSUE THREAD

**Issue by bjoluc** [CN-UPB/Pishahang#16]
Many of the [current schemas](https://github.com/CN-UPB/Pishahang/tree/55ba2371ad7546467a95c4789d508bfd5c64a626/schemas) contain redundant definitions, making it hard to understand what is unique about certain schema files, and even harder to maintain schemas.

Examples:
* Descriptors and their records: Every record schema seems to copy the corresponding descriptor schema instead of referencing it.
* The unit definitions at the top of almost each schema file

json-schema supports referencing across files to solve this problem.

**Comment by hadik3r** [comment]
It's a good idea. Also, the complex service and AWS service descriptors need to be merged with network services (on the service level, not function level). There is no need to separate them anymore.
