### ISSUE TITLE
Service Lifecycle Manager does not make use of OOP

### ISSUE THREAD

**Issue by bjoluc** [CN-UPB/Pishahang#18]
The SLM basically is a ~3000 LOC class that manages the contents of some dictionaries while interacting with other components. Understanding its code can be extremely hard, not to mention maintainability. A large amount of repetitive code (frequently passing the same parameters, dictionary accesses) could be made obsolete using OOP.

Quick Example: Services. Information on them is stored in a single dictionary; almost all service-related methods require a `serv_id` argument (and there are a lot of them obviously). Introducing a `Service` class, service-related functionalities would be coupled to service-related data, making the purpose and scope of both of them easier to understand.

**Comment by hadik3r** [comment]
Agreed!

**Comment by bjoluc** [comment]
The same thing (except for the file size) applies to the Function Lifecycle Management plugin as well.
