### ISSUE TITLE
[RFC] The future of son-catalogue-repos?

### ISSUE THREAD

**Issue by bjoluc** [CN-UPB/Pishahang#19]
`son-catalogue-repos` is a Ruby-based microservice that offers an HTTP REST API with CRUD operations for various entities stored in MongoDB. Internally, it validates request data using the corresponding JSON schemas.

Advantages of "the catalogue repos":
* Being a layer between other microservices and MongoDB, it enforces schemas for MongoDB documents
* By using an HTTP API, it does not make restrictions to the microservices' programming languages

Disadvantages:
* Microservices have to create model classes for interaction with the catalogue-repos API themselves, which most of them don't
* Adding models to the catalogue repos requires implementing HTTP APIs for them (which, in the current setup, is way more low-level than it could be)
* It restricts the query options to the ones implemented in the HTTP API

Considering the fact that all database-interacting microservices are either already implemented in Python, or in the process of being ported to Python, the overhead of an HTTP API seems unnecessary to me. Instead, using a set of shared MongoEngine models embedded in the `manobase` package would:
* simplify database interactions in microservices
* allow more advanced queries by using MongoEngine instead of a REST API
* provide model classes for microservices by default, and, by enabling in-editor type hints, help to prevent runtime validation errors
* improve maintainability (one API less to maintain)

This approach would therefore tackle all of the above disadvantages, at the cost of loosing cross-language validation features. In my opinion, that's worth it. What do you think?

**Comment by hadik3r** [comment]
The microservices should be loosely-coupled and they should be able to be written in any programming languages. Also, the data that is stored in the repositories should also be available to the external entities (like to another MANO instance in a hierarchical model). All being said, I think it's better to keep catalogue as it is or make a python-based catalogue.

**Comment by bjoluc** [comment]
Thanks for the quick reply! I agree; availability to external services is indeed a show stopper for direct database access. Hence closing this. I think we will go the route of using a higher-level framework for the catalogue repos then to at least improve maintainability.
